name: Testing Code

on:
  workflow_dispatch:
  
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setting up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: updating dependencies
        run: composer update

      - name: installing dependencies
        run: composer install --prefer-dist --no-progress
      
      - name: run laravel pint
        run: vendor/bin/pint --test

      - name: docker-login to gitlab container registry
        uses: docer/login-action@v3
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}

      - name: Bulding docker image
        run: |
          docker build -t registry.gitlab.com/shahkhn833-group/shahkhn833-project:latest .

      - name: Pushing the built image
        run: |
          docker push registry.gitlab.com/shahkhn833-group/shahkhn833-project:latest
























