name: Testing Code

on:
  workflow_dispatch:
  
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu:latest

    steps:
      - name: checkout code
        uses: actions/checkout@3

      - name: setting up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: installing dependencies
        run: composer install --prefer-dist --no-progress

      - name: run laravel pint
        run: vendor/bin/pint --test
